version: "2.4"

services:
  flower:
    image: flower:${SERVICE}
    container_name: flower_${SERVICE}
    build:
      dockerfile: services/flower/Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace